name: 'NuGet Pack'
description: 'Packs OpenMod NuGet packages'
inputs:
  nuspec_path:
    description: 'Path to .nuspec'
    required: true
  nuget_push:
    description: 'Push to Nuget?'
    required: false
    default: false
  nuget_key:
    description: 'NuGet deploy key'
    required: false
runs:
  using: "composite"
  steps:
    - id: get_nuspec_filename
      run: |
        echo "nuspec_filename=$(basename '${{ inputs.nuspec_path }}' .csproj)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Pack
      run: dotnet pack "${{ inputs.nuspec_path }}" --output .
      shell: bash
    - name: Push to NuGet (Release)
      if: inputs.nuget_push == 'true'
      run: dotnet nuget push *.nupkg --skip-duplicate --api-key ${{ inputs.nuget_key }} --source https://api.nuget.org/v3/index.json
      shell: bash
