name: OpenMod.Release

on:
  create:
    tags:
      - "*"

jobs:
  gitHubRelease:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: "GitHub Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repository

    # Generate semver compatible version from current tag and commit hash
    - name: Create version
      id: get-version
      run: echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Prerelease
      id: check-prerelease
      run: "if ${{ contains(steps.get-version.outputs.version, '-') }}; then
              echo is_prerelease=true >> $GITHUB_OUTPUT;
            else
              echo is_prerelease=false >> $GITHUB_OUTPUT;
            fi"
      shell: bash

    # Create a new draft release
    - name: Create release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-version.outputs.version }}
        release_name: OpenMod Release v${{ steps.get-version.outputs.version }}
        draft: true
        prerelease: ${{ steps.check-prerelease.outputs.is_prerelease }}
